config/routes.rb
Rails.application.routes.draw do
  get 'barcodes/scan'
  get 'barcodes/search'
  get 'dashboard/Index'
  get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :stocks do
    member do
      get 'amount'
    end
  end
  resources :clients

  resources :sales do
    member do
      get :download_recipe
    end
  end

  # Ajuste a rota para 'dashboard' aqui, incluindo a ação de exportar para Excel
  resources :dashboard, only: [:index] do
    collection do
      get :export_to_excel, format: :xlsx
      get :export_week_sales, as: 'export_week_sales'
      get :export_csv, as: :dashboard_export_csv
    end
  end
  
  resources :users, only: %i[new create]
  resources :sessions, only: %i[new index create destroy]

  delete '/logout', to: 'sessions#destroy', as: :logout

  get '/dashboard/sales', to: 'dashboard#sales', as: :dashboard_sales
  get '/dashboard/compare-months', to: 'dashboard#compare_months', as: :dashboard_compare_months
  get '/dashboard/stock', to: 'dashboard#stock', as: :dashboard_stock
  get '/dashboard/export', to: 'dashboard#export', as: :dashboard_export_to_excel
  get 'dashboard/export_to_excel', to: 'dashboard#export_to_excel', as: :dashboard_export
  

  get 'details_by_month/:month', to: 'dashboard#details_by_month', as: 'details_by_month'

  

  get 'login', to: 'sessions#index'
  post 'login', to: 'sessions#create'

  get 'login/new', to: 'sessions#new'
  post 'sessions/new', to: 'sessions#create'

  # Route for the scan page (input field to scan barcode)
  get 'barcodes/scan', to: 'barcodes#scan'
  

  resources :barcodes do
    post 'finish_sale', on: :collection
    post 'cancel_sale', on: :collection
  end

  # Route to handle the barcode search
  post 'barcodes/search', to: 'barcodes#search'

  root 'home#index'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :sale

  def create_recipe
    @recipe = Recipe.new(recipe_params)
    @recipe.save
  end

  def recipe_note
    @recipe_note = "Nota de venda\n\n" +
                   "Data: #{sale.created_at.strftime('%d/%m/%Y %H:%M')}\n\n" +
                   "Detalhes da venda:\n" +
                   "Produto: #{sale.stock.name}\n" +
                   "Quantidade: #{sale.quantity}\n" +
                   "Preço final: #{sale.total_price}R$\n\n" +
                   "Califórnia Café Bar\n" +
                   "Telefone (16) 99241-4255" 

  end

  def recipe_params
    params.require(:recipe, :sale).permit(:stock_id, :quantity, :total_price, :user_id)
  end
end

app/models/sale.rb
class Sale < ApplicationRecord


   belongs_to :stock
  
  has_one :recipe
  before_create :calculate_total_price
  
  validate :update_stock_quantity
  after_create :create_recipe, :test

  validates :stock, presence: true

  private
 
    #add the logic to deal with the payment method
  def calculate_total_price
    self.total_price = quantity * stock.price
  end

  def test
    puts "SDISUEGIUSYERTHUNTUN8EUYRGYHUNRU T"
  end

  
  def update_stock_quantity
    if stock.amount < quantity
      errors.add(:quantity, "can't be greater than stock amount")
      throw :abort
    else
      stock.amount -= quantity
      stock.save
    end
  end
  

  def create_recipe
    Recipe.create(
      sale: self,
      stock_id:,
      quantity:,
      total_price:
    )
  end
end

app/models/session.rb
class Session < ApplicationRecord
  def destroy
    reset_session
    redirect_to root_url, notice: 'Logged out successfully!'
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  # Callback to set a default barcode if the item is a "salgado"
  before_save :set_default_barcode, if: :is_salgado?

  # Associations
  belongs_to :user
  has_many :sales
  

  # Validations
  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :amount, :price, presence: true

  # Conditional validation for barcode only if it's not a "salgado"
  validates :barcode, presence: true, uniqueness: true, length: { is: 13 }, unless: :is_salgado?

  private

  # Method to set a default barcode value for "salgados"
  def set_default_barcode
    self.barcode = "1111111111111" # default barcode to all salgados
  end

  # Method to check if the stock is a "salgado"
  def is_salgado?
    self[:is_salgado] == true
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true

  has_many :stock
  has_secure_password
end

app/controllers/clients_controller.rb
class ClientsController < AuthenticatedController
  def create
    @clients = Client.new(client_params)
    @clients.user = User.find(session[:user_id]) if session[:user_id]
    if @clients.save
      redirect_to clients_url
    else
      puts @clients.errors.full_messages
      render :new
    end
  end

  def index
    @clients = Client.where(user_id: session[:user_id])
  end

  def new
    @clients = Client.new
    @stock = Stock.where(user_id: session[:user_id])
  end

  def destroy
    @clients = Client.find(params[:id])
    @clients.destroy
    redirect_to clients_url
  end

  private

  def client_params
    params.require(:client).permit(:name, :user_id)
  end
end

app/helpers/barcode_helper.rb
module BarcodeHelper
end

app/helpers/barcodes_helper.rb
module BarcodesHelper
end

app/helpers/beehives_helper.rb
module BeehivesHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sell_helper.rb
module SellHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/create_sale.html.erb
<!-- app/views/clients/create_sale.html.erb -->
<h1>Create Sale for <%= @clients.name %></h1>
  <%= link_to 'Back to Index', root_path %>

<%= form_with(url: create_sale_client_path(@clients), local: true) do |form| %>
  <div>
    <%= form.label :stock_id, 'Stock ID' %>
    <%= form.number_field :stock_id %>
  </div>

  <div>
    <%= form.label :quantity, 'Quantity' %>
    <%= form.number_field :quantity %>
  </div>

  <%= form.hidden_field :user_id, value: session[:user_id] %>

  <%= form.submit 'Create Sale' %>
<% end %>

app/views/clients/index.html.erb
<!-- app/views/clients/index.html.erb -->

<%# <head>
  <style>
    h1 {
      text-align: center;
    }
   
  </style>
</head> %>
<h1>Clients</h1>

<table>
  <thead>
      <%= link_to 'Back to Index', root_path %>

       <%= link_to 'Create Sale', new_sale_path %>

       <td><%= link_to 'Create Client', '/clients/new' %></td>
    <tr>
      <th>Name</th>
      <th>Balance</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
   <% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.balance %></td>
    <td>
      <%= form_with url: client_path(client), method: :delete do %>
        <%= submit_tag 'Delete Client' %>
      <% end %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<!-- app/views/clients/new.html.erb -->
<h1>New Client</h1>
  <%= link_to 'Back to Index', root_path %>

<%= form_with(model: @clients, local: true) do |form| %>
  <div>
    <%= form.label :name, 'Name' %>
    <%= form.text_field :name %>
 
  </div>

  <%= form.submit 'Create Client' %>
<% end %>